INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AL',
'1',
' Alabama',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AK',
'2',
' Alaska',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AZ',
'4',
' Arizona',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AR',
'5',
' Arkansas',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CA',
'6',
' California',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CO',
'8',
' Colorado',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CT',
'9',
' Connecticut',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('DE',
'10',
' Delaware',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('DC',
'11',
' District of Columbia',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('FL',
'12',
' Florida',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GA',
'13',
' Georgia',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('HI',
'15',
' Hawaii',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ID',
'16',
' Idaho',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('IL',
'17',
' Illinois',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('IN',
'18',
' Indiana',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('IA',
'19',
' Iowa',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('KS',
'20',
' Kansas',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('KY',
'21',
' Kentucky',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LA',
'22',
' Louisiana',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ME',
'23',
' Maine',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MD',
'24',
' Maryland',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MA',
'25',
' Massachusetts',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MI',
'26',
' Michigan',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MN',
'27',
' Minnesota',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MS',
'28',
' Mississippi',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MO',
'29',
' Missouri',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MT',
'30',
' Montana',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NE',
'31',
' Nebraska',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NV',
'32',
' Nevada',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NH',
'33',
' New Hampshire',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NJ',
'34',
' New Jersey',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NM',
'35',
' New Mexico',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NY',
'36',
' New York',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NC',
'37',
' North Carolina',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ND',
'38',
' North Dakota',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('OH',
'39',
' Ohio',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('OK',
'40',
' Oklahoma',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('OR',
'41',
' Oregon',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PA',
'42',
' Pennsylvania',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('RI',
'44',
' Rhode Island',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SC',
'45',
' South Carolina',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SD',
'46',
' South Dakota',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TN',
'47',
' Tennessee',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TX',
'48',
' Texas',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('UT',
'49',
' Utah',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('VT',
'50',
' Vermont',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('VA',
'51',
' Virginia',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('WA',
'53',
' Washington',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('WV',
'54',
' West Virginia',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('WI',
'55',
' Wisconsin',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('WY',
'56',
' Wyoming',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AS',
'60',
' American Samoa',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GU',
'66',
' Guam',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MP',
'69',
' Northern Mariana Islands',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PR',
'72',
' Puerto Rico',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
INSERT INTO `chhsdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('VI',
'78',
' U.S. Virgin Islands',
'testuser',
CURRENT_TIMESTAMP,
'testuser',
CURRENT_TIMESTAMP);
