 
 

INSERT INTO chhsdb.USERS (USR_USER_ID, USR_PASSWORD, USR_FIRSTNAME, USR_MIDDLENAME, USR_LASTNAME, CREATE_USER_ID, CREATE_TS, UPDATE_USER_ID, UPDATE_TS) 
	VALUES ('testuser', 'test', 'John', 'Joe', 'Smith', 'testuser', CURRENT_TIMESTAMP, 'testuser', CURRENT_TIMESTAMP)
 
 




